variables:
  ARM_PASS: $(adminPass)

trigger:
- none 

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'dzf_pipe_azure_con'
    subscriptionId: 'd41ec4e7-5694-40d1-a55b-2a245d12e7b0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'dzf_pipe_azure_testrg'
    location: 'East US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
