name: Trigger auto deployment for dzfcapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dzfcapp-AutoDeployTrigger-5aa1cd0f-b42d-435e-a92c-f5dbbef28c51.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DZFCAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DZFCAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DZFCAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.DZFCAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DZFCAPP_REGISTRY_PASSWORD }}
          containerAppName: dzfcapp
          resourceGroup: dzfcapp
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


